server:
  port: 8102

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/author_db?useSSL=false&serverTimezone=UTC
    username: libuser
    password: libpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
