server:
  port: 8222

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      routes:
        - id: book_route
          uri: lb://book-service
          predicates:
            - Path=/api/books/**
          filters:
            - StripPrefix=1
        - id: author_route
          uri: lb://author-service
          predicates:
            - Path=/api/authors/**
          filters:
            - StripPrefix=1
        - id: loan_route
          uri: lb://loan-service
          predicates:
            - Path=/api/loans/**
          filters:
            - StripPrefix=1
