server:
  port: 8103

spring:
  application:
    name: server:
  port: 8103

spring:
  application:
    name: loan-service

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/loan_db?useSSL=false&serverTimezone=UTC
    username: libuser
    password: libpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/loan_db?useSSL=false&serverTimezone=UTC
    username: libuser
    password: libpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
